services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  redis:
    image: redis:alpine
    container_name: maple-redis
    ports:
      - "6379:6379"
    volumes:
      - ~/redis-data:/data
    command: redis-server --appendonly yes --requirepass "sixclassguys"
    restart: always
  rabbitmq:
    image: cycling9/rabbitmq-delayed-message-exchange:3.12-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" # 관리자 대시보드
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest